NASA-IMPACT/veda-data

transformation-scripts/example-template/example-geoglam-ingest.ipynb
This notebook shows an example workflow for a data provider who wants to add a new data set to the VEDA Dashboard. The examples uses the GEOGLAM June 2023 output (CropMonitor_2023_06_28.tif)* output for this walkthrough.
*Please note the actual .tif file itself has not been added to this PR. Is there a best place to store this dataset? cc' @jsignell @j08lue
(originally open as a PR on `veda-docs` but moved here as deemed more appropriate.)
=> add example dataset upload nb, with geoglam June

.github/ISSUE_TEMPLATE/new-dataset.yaml
Add a link to the SPDX list for valid license identifiers.
=> Add link for valid SPDX license identifiers

transformation-scripts/cmip6-kerchunk/generate-cmip6-kerchunk-historical.ipynb, transformation-scripts/cmip6-kerchunk/publish-cmip6-kerchunk-stac.ipynb
Documentation for CMIP6 Kerchunk Demo data. Once this is merged I could include links in the final dataset page in the dashboard. I will be updating the STAC notebook to use the staging API and probably using `DEMO` in place of `TEST`
=> Add cmip6 kerchunk

README.md
There was [an update](https://github.com/NASA-IMPACT/veda-data/pull/84) that moved from a custom script in `scripts/validate_collections.py` to validation via pytest.  This just updates the readme to match that
=> update readme to use pytest for validation

ingestion-data/collections/hls-l30-002-ej-reprocessed.json, ingestion-data/collections/hls-s30-002-ej-reprocessed.json
Fix a metadata issue in older hand curated environmental justice hls reprocessed collections.
=> fix: remove incorrect provider property from hls reprocessed collections

ingestion-data/production/discovery-items/houston-urbanization.json
Made discovery-items prefix more specific to avoid .aux.tif that may have caused the ingest to error
=> fix: houston-urbanization discovery prefix fix

ingestion-data/production/discovery-items/nightlights-hd-monthly.json
Extend nightlights-hd-monthly.json discover config regex to catch abbreviated place names
=> Fix nightlights-hd-monthly discovery config

ingestion-data/production/collections/modis-annual-lai-2003-2020.json, ingestion-data/production/collections/oco2-geos-l3-daily.json, ingestion-data/production/discovery-items/modis-annual-lai-2003-2020.json, ingestion-data/production/transfer-config/modis-annual-lai-2003-2020.json
Add `modis-annual-lai-2003-2020` and `oco2-geos-l3-daily` datasets to production.
=> Add modis-annual-lai-2003-2020 and oco2-geos-l3-daily

.github/workflows/pr.yml, ingestion-data/testing/dataset-config/test.json
https://github.com/NASA-IMPACT/veda-data/issues/180
=> feat: add automated publishing workflow with no-ops

ingestion-data/production/dataset-config/ps-portage-tornadoes-2024.json, ingestion-data/production/transfer-config/ps-portage-tornadoes-2024.json, ingestion-data/staging/dataset-config/ps-portage-tornadoes-2024.json
Add stac collection and ingestion config for `ps-portage-tornadoes-2024`
=> feat(dataset): add ps-portage-tornadoes-2024 dataset config

ingestion-data/production/dataset-config/ps-greenfield-pre-tornadoes-2024.json, ingestion-data/production/transfer-config/ps-greenfield-pre-tornadoes-2024.json, ingestion-data/staging/dataset-config/ps-greenfield-pre-tornadoes-2024.json
Add stac collection and ingestion config for `ps-greenfield-pre-tornadoes-2024`
=> feat(dataset): add ps-greenfield-pre-tornadoes-2024 dataset config

ingestion-data/production/dataset-config/ps-lakeview-winchester-tornadoes-2024.json, ingestion-data/production/transfer-config/ps-lakeview-winchester-tornadoes-2024.json, ingestion-data/staging/dataset-config/ps-lakeview-winchester-tornadoes-2024.json
Add stac collection and ingestion config for `ps-lakeview-winchester-tornadoes-2024`
=> feat(dataset): add ps-lakeview-winchester-tornadoes-2024 dataset config

ingestion-data/production/dataset-config/tornadoes-2024-dow-rhohv-greenfield.json, ingestion-data/production/transfer-config/tornadoes-2024-dow-rhohv-greenfield.json, ingestion-data/staging/dataset-config/tornadoes-2024-dow-rhohv-greenfield.json
Add stac collection and ingestion config for `tornadoes-2024-dow-rhohv-greenfield`
=> feat(dataset): add tornadoes-2024-dow-rhohv-greenfield dataset config

ingestion-data/production/dataset-config/ps-tornadoes-2024-difference.json, ingestion-data/production/transfer-config/ps-tornadoes-2024-difference.json, ingestion-data/staging/dataset-config/ps-tornadoes-2024-difference.json
Add stac collection and ingestion config for `ps-tornadoes-2024-difference`
=> feat(dataset): add ps-tornadoes-2024-difference dataset config

ingestion-data/production/dataset-config/lakeview-nightlights-tornadoes-2024.json, ingestion-data/production/transfer-config/lakeview-nightlights-tornadoes-2024.json, ingestion-data/staging/dataset-config/lakeview-nightlights-tornadoes-2024.json
Add stac collection and ingestion config for `lakeview-nightlights-tornadoes-2024`
=> feat(dataset): add lakeview-nightlights-tornadoes-2024 dataset config

ingestion-data/production/dataset-config/greenville-nightlights-tornadoes-2024.json, ingestion-data/production/transfer-config/greenville-nightlights-tornadoes-2024.json, ingestion-data/staging/dataset-config/greenville-nightlights-tornadoes-2024.json
Add stac collection and ingestion config for `greenville-nightlights-tornadoes-2024`
=> feat(dataset): add greenville-nightlights-tornadoes-2024 dataset config

.github/workflows/pr.yml, scripts/generate-mdx.py
This PR updates pr.yml so that it opens a corresponding veda-config PR with the generated MDX file. 
I'm thinking it's best to separate the publishing collections to production in another PR.
=> feat: update pr.yml to open veda-config pr 

.github/workflows/pr.yml, .github/workflows/promote.yml, .github/workflows/promotion-checker.yml
- Updates pr.yml to no longer trigger the intermediate promotion checker workflow
- Updates the promotion-checker workflow to check that the PR was merged and approved and checks that `pr.yml` was run and completed successfully before triggering the promote.yml workflow
- Updates promote.yml workflow to be triggered only on workflow dispatch
- Updates promotion checker to pass PR number to promote workflow so we can identify which PR is associated with the promotion run.
=> feat: change promotion checker to run on PR merge

.github/workflows/promotion-checker.yml
Addresses https://github.com/NASA-IMPACT/veda-data/actions/runs/13147286952/job/36688076780
```
Run WORKFLOW_STATUS=$(gh run list --repo NASA-IMPACT/veda-data --branch feat/ida-ndwi-difference-TEST-PROMOTE-2 --workflow "pr.yml" --json status --jq '.[0].status // "not found"')
WORKFLOW_STATUS=$(gh run list --repo NASA-IMPACT/veda-data --branch feat/ida-ndwi-difference-TEST-PROMOTE-[2](https://github.com/NASA-IMPACT/veda-data/actions/runs/13147286952/job/36688076780#step:4:2) --workflow "pr.yml" --json status --jq '.[0].status // "not found"')
echo "Previous workflow (pr.yml) status: $WORKFLOW_STATUS"
if [ "$WORKFLOW_STATUS" != "completed" ]; then
echo "Previous workflow (pr.yml) did not complete successfully. Exiting..."
exit 1
fi
shell: /usr/bin/bash -e {0}
env:
PR_NUMBER: …
```
=> fix: add github token env var

.github/workflows/promotion-checker.yml
Changed action to use Github CLI `gh run download` command because the action `download-artifact` only works within the same workflow run to download artifacts.
=> fix: use github cli to download run id artifact

.github/workflows/promotion-checker.yml
Environment variables set using `echo ... >> $GITHUB_ENV` are only available within the same job.
=> fix: move read run id to promotion workflow trigger job

.pre-commit-config.yaml, README.md, transformation-scripts/collection-and-item-ingest.ipynb
Update links to docs.openveda.cloud after it was [re-organized](https://github.com/NASA-IMPACT/veda-docs/pull/203)
=> fix(docs): update links after veda docs site re-org

.github/workflows/pr.yml, ingestion-data/staging/dataset-config/test-added.json, ingestion-data/staging/dataset-config/test.json
https://github.com/NASA-IMPACT/veda-data/issues/312
=> feat: update workflow to process all added, changed, modified, and renamed dataset-config files

.github/workflows/ci.yaml, .github/workflows/pr.yml, .github/workflows/promote.yml, .github/workflows/promotion-checker.yml
https://github.com/NASA-IMPACT/veda-architecture/issues/569
-  actions/checkout@v4 pinned to [v4.2.2](https://github.com/actions/checkout/commit/11bd71901bbe5b1630ceea73d27597364c9af683)
- actions/setup-python@v4 pinned to [v5.4.0](https://github.com/actions/setup-python/releases/tag/v5.4.0) and [v4.8.0](https://github.com/actions/setup-python/commit/b64ffcaf5b410884ad320a9cfac8866006a109aa)
- tj-actions/changed-files@v45 pinned to [v46.0.1](https://github.com/tj-actions/changed-files/commit/2f7c5bfce28377bc069a65ba478de0a74aa0ca32)
- actions/setup-python@v5 pinned to [v5.4.0](https://github.com/actions/setup-python/releases/tag/v5.4.0)
- actions/upload-artifact@v4 pinned to [v4.6.1](https://github.com/actions/upload-artifact/commit/4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1)
=> fix: use commit hash in actions

.github/workflows/promotion-checker.yml
https://github.com/NASA-IMPACT/veda-data/issues/330
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths
This will limit the workflow to running if the PR is not a dataset-config *.json file change. `path` creates a condition where at least one path matches a pattern in the paths filter, the workflow runs.
=> feat: PR/promotion checker should not be invoked for non-data changes

.github/workflows/pr.yml, .github/workflows/promote.yml, scripts/promote_collection.py, scripts/promote_dataset.py
- renames `promote_collection.py` as `promote_dataset.py`. New `promote_collection.py` now includes a script to post to the `veda_collection_pipeline` DAG. Dataset promotion scripts which is now in `promote_dataset.py` is unchanged.
- `pr.yml` and `promote.yml` include logic for both `ingestion-data/staging/dataset-config/` and `ingestion-data/staging/collections/` directories
=> Include collection promotion

scripts/promote_collection.py
Do print informative statement if env variables are missing but do not print values
```
>>> stage="production"
>>> username_env=None
>>> password_env="pants"                                                                                                   
>>> print(f"Missing one or more environment variables: stage undefined={stage==None}, username undefined={username_env==None}, password undefined={password_env==None}")
Missing one or more environment variables: stage undefined=False, username undefined=True, password undefined=False
```
=> fix: remove print user info

.github/workflows/pr.yml
Replace [@tj-actions/changed-files](https://github.com/tj-actions/changed-files)
Addresses https://github.com/NASA-IMPACT/veda-architecture/issues/570
NOTE: The workflow trigger uses a glob pattern match (`ingestion-data/staging/dataset-config/**.json`), whereas the current bash uses a regex pattern match (`^ingestion-data/staging/dataset-config/.*\.json$`)
- **Alternative**
- Append [path](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-path) globs to the `diff` cmd
- [git diff [\<options\>] \<commit\>..\<commit\> [--] [\<path\>…​]](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-gitdiffoptionscommitcommit--path)
- **Considerations**: 
- The git-based alternative could be easier to misapply + fail silently (e.g. shell expansion, pattern validation) 
- Align with …
=> ci: replace `tj-actions`

ingestion-data/production/discovery-items/scheduled/eis-fedsoutput-lfarchive.json, ingestion-data/production/discovery-items/scheduled/eis-fedsoutput-snapshot.json
This PR adds the configs currently used to schedule production vector ingests.
=> feat(scheduled-dags): add currently scheduled vector ingest configs
